# Generated by Django 3.1.4 on 2020-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productLine', models.CharField(max_length=50)),
                ('textDescription', models.CharField(max_length=50)),
                ('htmlDescription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='productLines2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productLine', models.CharField(max_length=50)),
                ('textDescription', models.CharField(max_length=50)),
                ('htmlDescription', models.CharField(max_length=50)),
            ],
        ),
    ]
